#!/usr/bin/env bash

# Update repositories and install nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Ensure Nginx is listening on port 80
sudo sed -i 's/.*listen\(.*\)80.*/listen 80;/g' /etc/nginx/sites-available/default

# Create a default HTML page with 'Hello World!'
echo "<html><body>Hello World!</body></html>" | sudo tee /var/www/html/index.html > /dev/null

# Restart Nginx
sudo kill -s HUP $(cat /var/run/nginx.pid)

