#!/usr/bin/env bash
# This script displays information about users from the /etc/passwd file.

# Path to the /etc/passwd file
passwd_file="/etc/passwd"

# Use a while loop to read each line from the passwd file
while IFS=":" read -r username password uid gid info home shell
do
    # Extract user information and format the output
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. USER ID's place is protected by the passcode $password, more info about the user here: $uid $info"
    echo "-----------------------------------------"
done < "$passwd_file"
